version: 2
updates:
  - package-ecosystem: deno
    directories:
      - /
      - /packages/api
      - /packages/client
      - /packages/date-range
      - /packages/explode
      - /packages/fs
      - /packages/json-schema
      - /packages/server
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directories:
      - /.github/actions
      - /.github/workflows
    schedule:
      interval: weekly
