name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc
      - run: deno check --frozen
      - run: deno lint
      - run: deno fmt --check
      - run: deno task test
      - run: deno publish --dry-run
